### ISSUE TITLE
Make moving homepage photos smaller

### ISSUE THREAD

**Issue by CantabileMusic** [benbillbob/cantabilemusic#8]

**Comment by benbillbob** [comment]
Better?

**Comment by CantabileMusic** [comment]
Yes thanks.  

www.cantabilemusic.com.au - Sutherland Shire Children's Choir: vocal groups for children and teens- Private lessons in singing, piano & HSC music
www.natalieclaire.com.au - Soloist for Weddings/Funerals/Events - Cantabile Quartet/Choir - Natalie Claire Jazz Band
Ph: 0415 796 095
